GET http://localhost:3000/

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs
### with pagination
GET http://localhost:3000/songs?page=1&limit=2

### FETCH SONG BY ID REQUEST
GET http://localhost:3000/songs/3

### CREATE NEW SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvcGhpYS5icm93bkBleGFtcGxlLmNvbSIsInVzZXJJZCI6NCwiYXJ0aXN0SWQiOjQsImlhdCI6MTc2NTU5ODUyMSwiZXhwIjoxNzY1Njg0OTIxfQ.umwgfPO3Jl0TPBIslY19F7m1FLgTiWtTEHBUu1TuayM

{
  "title": "Moonlit Dreams",
  "releasedDate": "2025-12-20",
  "duration": "04:05",
  "lyrics": "Beneath the silver moon, our dreams take flight in the quiet night...",
  "artists": [5]
}




### UPDATE SONGS REQUEST
PUT http://localhost:3000/songs/12
Content-Type: application/json

{
  "lyrics": "I will love you till the end of time...\n\nStill I wander through the memories we made,\nEvery promise, every shadow, every step that never fades.\nWhen the nights get cold, I hold the thought of you as light,\nGuiding me through everything, a fire burning bright.\n\nAnd if the world should fall apart before our eyes,\nI’ll keep your heart within my hands, I’ll keep your spirit in the skies.\nNo matter how the seasons change or how the storms may roll,\nYou’re the echo in my heartbeat, you're the story in my soul."
}

### DELETE SONGS REQUEST
DELETE http://localhost:3000/songs/17

###################################################################

### Create new playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "Morning Vibes",
  "songs": [18, 19, 20],
  "user": 1
}


#####################################################################

### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "firstName": "Aarav",
  "lastName": "Sharma",
  "email": "aarav.sharma@example.com",
  "password": "password123"
}

### API KEY aarav.sharma@example.com  57e7ed91-d5a5-45f2-a5ca-28318914b6a2


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "david.wilson@example.com",
  "password": "password123"
}

# "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pY2hhZWwuam9obnNvbkBleGFtcGxlLmNvbSIsInN1YiI6MywiaWF0IjoxNzY1NTk1MDAyLCJleHAiOjE3NjU2ODE0MDJ9.IgXyR-2CtR7HuAk6YjGojQDfurDfcOhQ-MgU6_-T5A4"

### Profile
GET http://localhost:3000/profile
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsaWNlLnRheWxvckBleGFtcGxlLmNvbSIsInVzZXJJZCI6NiwiaWF0IjoxNzY1NTk4MjE4LCJleHAiOjE3NjU2ODQ2MTh9.c5eaZcbVXMqHq9JGqlGV4todphkGCdTRv8eASBy_2uM"


### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLndpbHNvbkBleGFtcGxlLmNvbSIsInVzZXJJZCI6NSwiYXJ0aXN0SWQiOjUsImlhdCI6MTc2NTYxMDQzMSwiZXhwIjoxNzY1Njk2ODMxfQ.D8aq4Aq6ihwqqoijINSo_Vy28G0r14Wk0Hhv7mdG1QM

### Validate 2FA
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLndpbHNvbkBleGFtcGxlLmNvbSIsInVzZXJJZCI6NSwiYXJ0aXN0SWQiOjUsImlhdCI6MTc2NTYxMDQzMSwiZXhwIjoxNzY1Njk2ODMxfQ.D8aq4Aq6ihwqqoijINSo_Vy28G0r14Wk0Hhv7mdG1QM
Content-Type: application/json

{
  "token": "578874"
}

### Disable 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvcGhpYS5icm93bkBleGFtcGxlLmNvbSIsInVzZXJJZCI6NCwiYXJ0aXN0SWQiOjQsImlhdCI6MTc2NTYwOTAxNywiZXhwIjoxNzY1Njk1NDE3fQ.TUkPfaDgb_TnjJpRZlrVDPhkh7cojc3ZIKz3KLZw7VU


### Profile with API KEY
GET http://localhost:3000/auth/profile
Authorization: Bearer 57e7ed91-d5a5-45f2-a5ca-28318914b6a2